# protein_name == "2lhd"
sequence = "TTYKLILNLKQAKEEAIKELVDAGTAEKYFKLIANAKTVEGVWTYKDEIKTFTVTE"
# sequence = "VLQVLSDWLTPLVATPPKTVSPEVGALKDTGRSLILRDLREKVVAYESNNPDPTGTTPTENDFATVRLEIFGPDGTQIGTTEGAGRMLYRQEKDEHFIAYFGEEITLNDGNVIRAGGLVDDARLTAGEHATFPAVVVSGPLRGAIGFRQFRPLVKESHTTYESSIVVYRR"
for aa in sequence: cmd._alt(string.lower(aa))
