#!/usr/bin/perl
# print the max and min of a column data.

if(defined($ARGV[0])){
	open IN, $ARGV[0] ;
}else {
	die "No input specified!"
}
if(defined($ARGV[1])){
	$n_col = $ARGV[1] ;
}else {
	$n_col = 1;
}
#print "$n_col\n";

$j = 0;
foreach (<IN>) {
	@line = split(' ',);
	foreach $i (0..$n_col-1){
		#push @{$energy[$i]}, $line[$i];
		$energy[$i][$j] = $line[$i];
	}
	$j++;
}
foreach $i (0..$n_col-1){
	@sorted =sort{$a<=>$b}@{$energy[$i]} ;
	print "$i\t$sorted[0]\t$sorted[$#sorted]\n";
	#$#energy[$i] =-1; # clear the array
	$#sorted =-1; 
}
